# 练习3—8
travel = ['Nan Jing','Shang Hai','Chuan Xi','Xi Zang','Chong Qing']
print(travel)
print(sorted(travel))
print(travel)
print(sorted(travel,reverse = True))
print(travel)
travel.reverse()
print(travel)
travel.reverse()
print(travel)
travel.sort()
print(travel)
travel.sort(reverse = True)
print(travel)